### ISSUE TITLE
chat

### ISSUE THREAD

**Issue by Inkraja** [EQdkpPlus/plugin-chat#1]
Es fehlt in chat.css
.chatMessage { color:#000}.

Und ich persönlich würde die css auch unter templates suchen, nicht in includes.

Wirklich eine rote bubble, wenn eine Nachricht kommt? :)

![chat2](https://cloud.githubusercontent.com/assets/10184036/5560880/e2ac6ce8-8db1-11e4-9303-167931208ed5.JPG)

PS: ich teste hiermit auch mal das issue dingens ;)

**Comment by GodMod** [comment]
Was willst du denn dann statt ner roten Bubble?

**Comment by GodMod** [comment]
Und was das Issue Dingens angeht, werden wir wohl unseren Bugtracker im Forum weiterführen... er ist nur per default für Repos an...

**Comment by Inkraja** [comment]
blau wäre noch frei :D Aber ich denke grün ist absolut ausreichend, da ja sowieso das popup unten aufgeht...

**Comment by GodMod** [comment]
Hab mich halt an einer gewissen großen Seite in blau orientiert gehabt ;)
